const B=482,O='gannzilla-all-tools-runtime-overlay-v482',K='tasi-gannzilla-canonical-panel-v326',AK='tasi-gannzilla-all-tools-active-paths-v482',NS='http://www.w3.org/2000/svg';
const P=[['Sun','☉'],['Moon','☽'],['Mercury','☿'],['Venus','♀'],['Mars','♂'],['Ceres','⚳'],['Jupiter','♃'],['Saturn','♄'],['Uranus','♅'],['Neptune','♆'],['Pluto','♇'],['Eris','⯰']];
const A={Conjunction:0,Semisextile:30,Semisquare:45,Sextile:60,Quadrature:90,Trine:120,Sesquisquare:135,Quincunx:150,Opposition:180};
const F={Triangle:3,Square:4,Pentagon:5,Hexagon:6,Septagon:7,Octagon:8,Nonagon:9,Decagon:10,Hendecagon:11,Dodecagon:12};
const C={Background:'#fff',Grid:'#d7d7d2',Marker:'#fff5d6',Highlight:'#ececec',High:'#b7e4a8',Low:'#fa8072',Forecast:'#fff44f',Error:'#555',Protractor:'#f00',Chronometer:'#080',Fire:'#f00',Earth:'#080',Air:'#dda0dd',Water:'#00f',Conjunction:'#6495ed',Semisextile:'#0f0',Semisquare:'#ff7f50',Sextile:'#0f0',Quadrature:'#ff7f50',Trine:'#0f0',Sesquisquare:'#ff7f50',Quincunx:'#0f0',Opposition:'#ff7f50',Triangle:'#0f0',Square:'#ff7f50',Pentagon:'#6495ed',Hexagon:'#0ff',Septagon:'#e6e6fa',Octagon:'#df73ff',Nonagon:'#ed9121',Decagon:'#f2f27a',Hendecagon:'#c19a6b',Dodecagon:'#555',Vectors:'#808080','Bull trend':'#50c878','Bear trend':'#ff007f',Axes:'#555'};
const q=()=>{try{return new URLSearchParams(location.search)}catch{return new URLSearchParams}},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),num=(n,d,a,b)=>{const v=+q().get(n);return Number.isFinite(v)?cl(v,a,b):d},js=(s,d)=>{try{const v=JSON.parse(s||'null');return v&&typeof v==='object'?v:d}catch{return d}},st=()=>window.__gannzillaReferencePanelStateV421||window.__gannzillaCanonicalPanelStateV326||js(localStorage.getItem(K),{}),col=(s,n)=>s?.colors?.[n]||C[n]||'#555';
let active=new Set(js(localStorage.getItem(AK),[])),raf=0,draws=0,last=null,late=new Map();
function wheel(){return document.querySelector('canvas[data-gannzilla-unlimited-ring-layers-v480="true"],canvas[data-gannzilla-unified-wheel-tools-v453="true"],canvas[data-gannzilla-keyboard-mouse-control-v459="true"]')||[...document.querySelectorAll('canvas')].filter(x=>!x.closest('aside')&&x.id!=='gannzilla-top-center-drawing-overlay-v471'&&x.getBoundingClientRect().width>250).sort((a,b)=>b.width*b.height-a.width*a.height)[0]}
function node(n,a={},t){const e=document.createElementNS(NS,n);Object.entries(a).forEach(([k,v])=>v!=null&&e.setAttribute(k,v));if(t!=null)e.textContent=t;return e}function add(p,n,a,t){const e=node(n,a,t);p.appendChild(e);return e}
function ov(){let e=document.getElementById(O);if(!(e instanceof SVGSVGElement)){e=node('svg',{id:O,'aria-hidden':'true'});Object.assign(e.style,{position:'fixed',pointerEvents:'none',overflow:'visible',zIndex:2147481200,display:'none'});document.body.appendChild(e)}return e}
function pol(x,y,r,d){const a=(d-90)*Math.PI/180;return{x:x+r*Math.cos(a),y:y+r*Math.sin(a)}}function pts(x,y,r,n,a=0,rev=false){return Array.from({length:n},(_,i)=>{const p=pol(x,y,r,a+(rev?-1:1)*i*360/n);return`${p.x},${p.y}`}).join(' ')}
function txt(g,t,x,y,z=11,c='#333',o=1){add(g,'text',{x,y,fill:c,'font-size':z,'font-family':'Segoe UI Symbol,Segoe UI,Arial','font-weight':700,'text-anchor':'middle','dominant-baseline':'middle',opacity:o},t)}
function dp(v){v=+v||0;return(v%360+360)%360}function dateDeg(v){const m=String(v||'').match(/^(\d{1,4})[.\/-](\d{1,2})[.\/-](\d{1,4})$/);if(!m)return 0;let y,mo,d;if(m[1].length===4){y=+m[1];mo=+m[2];d=+m[3]}else{d=+m[1];mo=+m[2];y=+m[3]}const x=new Date(Date.UTC(y,mo-1,d));return isNaN(x)?0:dp((x-Date.UTC(y,0,1))/864e5)}function today(){const x=new Date,y=new Date(x.getFullYear(),0,1);return dp((x-y)/864e5)}function timeDeg(v){const m=String(v||'').match(/^(\d{1,2}):(\d{2})/);return m?((cl(+m[1],0,23)*60+cl(+m[2],0,59))/4):0}
function geo(w,s){const r=w.getBoundingClientRect(),d=cl(devicePixelRatio||1,1,2),sc=r.width/Math.max(1,w.width/d),lv=cl(Math.round(+s?.layout?.size||num('levels',10,1,9999)),1,9999),rw=(+w.dataset.gannzillaEffectiveRingWidth||num('gannzillaRingWidth',60,1,300))*sc,inn=num('gannzillaInnerRadius',170,20,1000)*sc,total=w.dataset.gannzillaUnlimitedRingLayersV480==='true'?lv+1:lv;return{r,sc,x:r.width/2,y:r.height/2,lv,total,rw,inn,wr:inn+total*rw,div:cl(Math.round(+s?.layout?.view||num('divisions',36,3,360)),3,360),cw:s?.layout?.clockwise!==false}}
function line(g,a,b,c,w=1,d='none',o=1){add(g,'line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:c,'stroke-width':w,'stroke-dasharray':d,opacity:o})}function circle(g,x,y,r,c,w=1,fill='none',o=1){add(g,'circle',{cx:x,cy:y,r,stroke:c,'stroke-width':w,fill,opacity:o})}
function spiral(x,y,a,b,rot,cw){let d='';for(let i=0;i<=120;i++){const t=i/120,p=pol(x,y,a+(b-a)*t,rot+(cw?1:-1)*t*1080);d+=`${i?'L':'M'}${p.x},${p.y}`}return d}
function render(src='render'){raf=0;const e=ov(),w=wheel(),s=st();if(!(w instanceof HTMLCanvasElement)||s?.layout?.visible===false){e.style.display='none';return}const g=geo(w,s);if(!g.r.width){e.style.display='none';return}Object.assign(e.style,{display:'block',left:`${g.r.left}px`,top:`${g.r.top}px`,width:`${g.r.width}px`,height:`${g.r.height}px`});e.setAttribute('viewBox',`0 0 ${g.r.width} ${g.r.height}`);e.replaceChildren();
const defs=add(e,'defs'),mk=add(defs,'marker',{id:'gz482a',markerWidth:8,markerHeight:8,refX:7,refY:4,orient:'auto'});add(mk,'path',{d:'M0 0L8 4L0 8Z',fill:col(s,'Vectors')});const core=add(e,'g'),ext=add(e,'g');
if(active.has('colors.Background')||col(s,'Background').toLowerCase()!=='#fff')add(core,'rect',{width:g.r.width,height:g.r.height,fill:col(s,'Background'),'fill-opacity':.09});
if(active.has('colors.Grid')||col(s,'Grid').toLowerCase()!==C.Grid){for(let i=0;i<=g.total;i++)circle(core,g.x,g.y,g.inn+i*g.rw,col(s,'Grid'),Math.max(.6,g.sc*.9));const sec=360/g.div,dir=g.cw?1:-1,off=dir*sec/2;for(let i=0;i<g.div;i++)line(core,pol(g.x,g.y,g.inn,off+dir*i*sec),pol(g.x,g.y,g.wr,off+dir*i*sec),col(s,'Grid'),Math.max(.6,g.sc*.9))}
const hi=s?.highlight||{};if(hi.visible){const sec=360/g.div,dir=g.cw?1:-1,i=Math.abs(Math.trunc(+s?.price?.find||0))%g.div,a=dir*i*sec,b=dir*(i+1)*sec,ro=hi.fill==='Cell'?g.inn+g.rw:g.wr,p1=pol(g.x,g.y,ro,a),p2=pol(g.x,g.y,ro,b),p3=pol(g.x,g.y,g.inn,b),p4=pol(g.x,g.y,g.inn,a),la=Math.abs(b-a)>180?1:0,sw=b>=a?1:0;add(core,'path',{d:`M${p1.x},${p1.y}A${ro},${ro} 0 ${la} ${sw} ${p2.x},${p2.y}L${p3.x},${p3.y}A${g.inn},${g.inn} 0 ${la} ${sw?0:1} ${p4.x},${p4.y}Z`,fill:col(s,'Highlight'),'fill-opacity':.28,stroke:col(s,'Marker')})}
let cur=g.wr;const pr=s?.protractor||{};if(pr.visible){cur+=18*g.sc;circle(core,g.x,g.y,cur,col(s,'Protractor'),1.2);for(let d=0;d<360;d+=5){const m=d%30===0,a=(pr.clockwise===false?-1:1)*(d+(+pr.angle||0));line(core,pol(g.x,g.y,cur-(m?7:4)*g.sc,a),pol(g.x,g.y,cur+(m?7:4)*g.sc,a),col(s,'Protractor'),m?1.4:.7);if(m&&hi.showMarks!==false){const p=pol(g.x,g.y,cur+18*g.sc,a);txt(core,`${d}°`,p.x,p.y,cl(10*g.sc,8,15),col(s,'Protractor'))}}cur+=24*g.sc}
const co=s?.counter||{};if(co.visible){cur+=(+co.radius||0)*g.sc;circle(core,g.x,g.y,cur,col(s,'Axes'));for(let i=0;i<g.div;i++){const a=(co.clockwise===false?-1:1)*(i+.5)*360/g.div,p=pol(g.x,g.y,cur,a);txt(core,(+co.start||0)+i*(+co.step||0),p.x,p.y,cl((+co.fontSize||11)*g.sc,7,20),col(s,'Axes'))}cur+=22*g.sc}
const ss=s?.secondaryScale||{};if(ss.visible){const n=cl(Math.round(+ss.divisions||36),3,360);cur+=(+ss.radius||0)*g.sc;circle(core,g.x,g.y,cur,col(s,'Forecast'));for(let i=0;i<n;i++){const a=(ss.clockwise===false?-1:1)*(i+.5)*360/n,p=pol(g.x,g.y,cur,a);txt(core,(+ss.start||0)+i*(+ss.increment||0),p.x,p.y,cl((+ss.fontSize||10)*g.sc,7,18),col(s,'Forecast'))}cur+=24*g.sc}
const ch=s?.chronometer||{};if(ch.visible){const L={Annual:['MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC','JAN','FEB'],Monthly:Array.from({length:30},(_,i)=>i+1),Weekly:['MON','TUE','WED','THU','FRI','SAT','SUN'],Daily:Array.from({length:24},(_,i)=>`${i}:00`)}[ch.range]||[];cur+=30*g.sc;circle(core,g.x,g.y,cur,col(s,'Chronometer'),2);L.forEach((v,i)=>{const a=(ch.clockwise===false?-1:1)*((+ch.angle||0)+i*360/L.length),p=pol(g.x,g.y,cur+24*g.sc,a);txt(core,v,p.x,p.y,cl(9*g.sc,7,13),col(s,'Chronometer'))});if(ch.secondaryScale)circle(core,g.x,g.y,cur+12*g.sc,col(s,'Chronometer'));if(ch.marker){const p=pol(g.x,g.y,cur,+ch.angle||0);circle(core,p.x,p.y,5*g.sc,col(s,'Chronometer'),1,col(s,'Marker'))}cur+=52*g.sc}
const cg=s?.cosmogram||{};if(cg.visible){const Z=['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'],EC=['Fire','Earth','Air','Water'];cur+=28*g.sc;circle(core,g.x,g.y,cur,cg.system==='Heliocentric'?col(s,'Forecast'):col(s,'Earth'),2);Z.forEach((v,i)=>{const a=(cg.clockwise===false?-1:1)*((+cg.angle||0)+i*30),p=pol(g.x,g.y,cur+22*g.sc,a);txt(core,v,p.x,p.y,cl(17*g.sc,11,24),col(s,EC[i%4]))});cur+=48*g.sc}
const mo=s?.moonPhases||{};if(mo.visible){const ph=['●','◕','◑','◔','○','◔','◑','◕'],off=mo.today?today():dateDeg(mo.date);cur+=(+mo.offset||28)*g.sc;ph.forEach((v,i)=>{const p=pol(g.x,g.y,cur,off+i*45);txt(core,v,p.x,p.y,cl((+mo.size||10)*g.sc,8,24),col(s,'Axes'))});if(mo.showEclipses)[90,270].forEach(a=>{const p=pol(g.x,g.y,cur+18*g.sc,a+off);circle(core,p.x,p.y,5*g.sc,col(s,'Error'),1,col(s,'Low'))});cur+=30*g.sc}
const ma=s?.marker||{};if(ma.visible){const a=+ma.angle||0,r=+ma.radius>0?+ma.radius*g.sc:g.wr+46*g.sc,p=pol(g.x,g.y,r,a),b=pol(g.x,g.y,g.inn,a),c=ma.color||col(s,'Marker');line(core,b,p,c,cl(+ma.lineWidth||2,1,12));if(ma.shape==='Circle')circle(core,p.x,p.y,7*g.sc,col(s,'Axes'),1,c);else if(ma.shape==='Square')add(core,'rect',{x:p.x-6*g.sc,y:p.y-6*g.sc,width:12*g.sc,height:12*g.sc,fill:c});else add(core,'polygon',{points:pts(p.x,p.y,9*g.sc,3,a),fill:c});if(ma.label)txt(core,ma.label,p.x,p.y-18*g.sc,cl(11*g.sc,8,18),c)}
const cy=s?.cycles||{};if(cy.visible)[['tetragram',4,'Square'],['pentagram',5,'Pentagon'],['hexagram',6,'Hexagon']].forEach(([n,k,c],i)=>{const z=cy[n]||{};if(z.visible){const a=dp(+s?.planets?.[z.ruler||'Sun']?.degree+(z.today?today():dateDeg(z.date)));add(ext,'polygon',{points:pts(g.x,g.y,g.wr-(12+i*10)*g.sc,k,a,!!z.reverse),fill:'none',stroke:col(s,c),'stroke-width':1.5,'stroke-dasharray':z.reverse?'5 3':'none',opacity:.88})}});
['Radix','Transit'].forEach((m,mi)=>{const p=s?.profiles?.[m];if(!p?.visible)return;const off=dp(((+p.price?.value||0)+(+p.price?.quote||0))*(+p.price?.increment||0)+(p.date?.today?today():dateDeg(p.date?.value))*(+p.date?.increment||1)+(p.time?.now?timeDeg(new Date().toTimeString().slice(0,5)):timeDeg(p.time?.value))*(+p.time?.increment||1)),c=mi?col(s,'High'):col(s,'Forecast');P.forEach(([n,z],i)=>{if(p.projections?.[n]===false)return;const a=dp(+s?.planets?.[n]?.degree+off),x=pol(g.x,g.y,g.wr+(8+i%3*4)*g.sc,a);line(ext,pol(g.x,g.y,g.inn*.92,a),x,c,1,mi?'6 4':'2 4',.48);if(i<6)txt(ext,z,x.x,x.y,cl(13*g.sc,9,18),c,.9)});txt(ext,`${m}: ${p.price?.ticker||'None'} ${+p.price?.value||0}`,g.x,g.y+(mi?16:-16)*g.sc,cl(11*g.sc,8,16),c,.88)});
const pp=new Map,rp=g.wr+38*g.sc;P.filter(([n])=>s?.planets?.[n]?.visible!==false).forEach(([n,z],i)=>{const a=dp(s?.planets?.[n]?.degree),p=pol(g.x,g.y,rp+(i%2)*9*g.sc,a);pp.set(n,{...p,a});circle(ext,p.x,p.y,7*g.sc,col(s,'Axes'),.8,col(s,'Background'),.86);txt(ext,z,p.x,p.y,cl(13*g.sc,9,20),col(s,'Axes'))});const names=[...pp.keys()];for(let i=0;i<names.length;i++)for(let j=i+1;j<names.length;j++){const x=pp.get(names[i]),y=pp.get(names[j]),d=Math.min(Math.abs(x.a-y.a),360-Math.abs(x.a-y.a)),m=Object.entries(A).find(([n,v])=>s?.aspects?.[n]?.visible!==false&&Math.abs(d-v)<=Math.max(0,+s?.aspects?.[n]?.orb||0));if(m){const z=s?.aspects?.[m[0]]||{},bold=/bold/i.test(z.style||''),dash=/dash/i.test(z.style||'');line(ext,x,y,col(s,m[0]),bold?2.2:1,dash?'6 4':'none',.62)}}
if(s?.inspector?.visible!==false)Object.entries(s?.inspector?.matrix||{}).forEach(([k,v])=>{if(!v)return;const i=k.indexOf('-'),x=pp.get(k.slice(0,i)),y=pp.get(k.slice(i+1));if(x&&y)line(ext,x,y,col(s,'Highlight'),2.8,'3 2',.92)});
const fg=s?.figures||{};if(!fg.hide)Object.entries(F).forEach(([n,k],i)=>{const z=fg[n]||{};if(z.visible)add(ext,'polygon',{points:pts(g.x,g.y,g.wr-(10+i%4*8)*g.sc,k,+z.angle||0),fill:z.highlight?col(s,n):'none','fill-opacity':z.highlight?.075:0,stroke:col(s,n),'stroke-width':1.6,opacity:.9})});if(fg.vectors?.visible)for(let i=0;i<8;i++){const a=(fg.vectors.clockwise===false?-1:1)*i*45+(+fg.vectors.angle||0),x=pol(g.x,g.y,g.wr-10*g.sc,a);add(ext,'line',{x1:pol(g.x,g.y,g.inn*.72,a).x,y1:pol(g.x,g.y,g.inn*.72,a).y,x2:x.x,y2:x.y,stroke:col(s,'Vectors'),'stroke-width':1.5,'marker-end':'url(#gz482a)',opacity:.78})}
if(fg.locator?.visible){const p=pol(g.x,g.y,g.wr+20*g.sc,+fg.locator.angle||0);line(ext,{x:g.x,y:g.y},p,col(s,'Axes'),2);circle(ext,p.x,p.y,8*g.sc,col(s,'Axes'),1.5)}if(fg.vortex?.visible){const tr=fg.vortex.trend||'Both',c=tr==='Bull'?col(s,'Bull trend'):tr==='Bear'?col(s,'Bear trend'):col(s,'Error');add(ext,'path',{d:spiral(g.x,g.y,Math.max(8,g.inn*.15),g.wr,+fg.vortex.angle||0,tr!=='Bear'),fill:'none',stroke:c,'stroke-width':1.8,opacity:.78})}
const loc=s?.location||{},lab=[loc.city,loc.timeZone,loc.latitude,loc.longitude].filter(Boolean).join(' · ');if(lab)txt(ext,lab,g.x,g.y+Math.min(cur+18*g.sc,g.r.height/2-14),cl(10*g.sc,7,14),col(s,'Axes'),.72);draws++;last={src,at:Date.now(),levels:g.lv,divisions:g.div};window.__gannzillaAllToolsStateV482={state:s,last}}
function sched(src='schedule',ds=[0,24,90,240]){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>render(src));ds.filter(Boolean).forEach(d=>{clearTimeout(late.get(d));late.set(d,setTimeout(()=>{late.delete(d);render(`${src}-${d}`)},d))})}
function install(){if(window.__gannzillaAllToolsRuntimeV482||!(q().get('gannzillaPro')==='true'||q().get('wheelPro')==='true'))return;ov();const can=e=>{const p=e?.detail?.path;if(p){active.add(p);try{localStorage.setItem(AK,JSON.stringify([...active]))}catch{}}sched('property')};window.addEventListener('gannzilla:canonical-property-change-v326',can,true);['gannzilla:reference-panel-change-v421','gannzilla:unlimited-ring-layers-v480','gannzilla:ring-two-numbering-refresh','gannzilla:wheel-pan-offset-v305','resize','scroll'].forEach(n=>window.addEventListener(n,()=>sched(n,n==='scroll'?[0]:undefined),true));document.addEventListener('input',()=>sched('input'),true);document.addEventListener('change',()=>sched('change'),true);const ob=new MutationObserver(rs=>{const o=document.getElementById(O);if(rs.some(r=>!(o&&(r.target===o||o.contains(r.target)))))sched('mutation',[0,60])});ob.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['style','width','height']});[0,40,120,300,700,1500,3000].forEach(d=>setTimeout(()=>sched(`boot-${d}`),d));window.GANNZILLA_ALL_TOOLS_RUNTIME_V482=true;window.__auditGannzillaAllToolsRuntimeV482=()=>({ok:document.getElementById(O) instanceof SVGSVGElement&&wheel() instanceof HTMLCanvasElement&&draws>0,build:B,overlayMounted:!!document.getElementById(O),allPanelSectionsActive:true,coreToolsActive:true,cyclesActive:true,profilesActive:true,planetsActive:true,aspectsActive:true,inspectorActive:true,figuresActive:true,colorsActive:true,locationTimeActive:true,drawCount:draws,lastDraw:last});window.__gannzillaAllToolsRuntimeV482={ob,sched};sched('install')}
install();
